services:
  - type: web
    name: restocafe-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: restocafe-super-secret-jwt-key-2024
      - key: JWT_EXPIRES_IN
        value: 12h

databases:
  - name: restocafe-db
    plan: free 