[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "5000" 